compute_environment: SLURM
distributed_type: MEGATRON_LM           
num_machines: 2
num_processes: 16                       # 2 nodes × 8 GPUs
mixed_precision: bf16

# --- Megatron-LM (tensor/pipeline) ---
megatron_lm_tp_size: 4                  # 4-way TP
megatron_lm_pp_size: 1                  # no pipeline
megatron_lm_reduce_scatter: true
megatron_lm_ddp_bucket_cap_mb: 25

# --- FSDP ---
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_activation_checkpointing: true