compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: ds_zero3.json
distributed_type: DEEPSPEED
dynamo_backend: 'NO'
machine_rank: 0
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
use_cpu: false